name: catatan_keuangan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dropdown_search: ^0.6.3
  flutter_masked_text2: ^0.9.1
  get: 4.3.8
  http: ^0:13.3
  intl: ^0.17.0
  path_provider: ^2.0.3
  sqflite: ^2.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  generate: true
  uses-material-design: true
